/**
 * @FileName: XC_LWC_MenuCtrl
 * @Description:
 * @Author: Graeme Ward
 * @ModificationLog:
 *-----------------------------------------------------------
 * Author            Date            Modification
 * Graeme Ward       8/16/2020         Created
 *-----------------------------------------------------------  
 */
public with sharing class XC_LWC_MenuCtrl {

//    @AuraEnabled
//    public static List<XC_LWC_MenuWrapper.MenuItem> getMenuItems(String menuName) {
//        return XC_LWC_MetadataCtrlHelper.getMenuItems(menuName);
//    }
}