/**
 * @FileName: XC_LWC_MenuCtrlTest
 * @Description:
 * @Author: Graeme Ward
 * @ModificationLog:
 *-----------------------------------------------------------
 * Author            Date            Modification
 * Graeme Ward       8/16/2020         Created
 *-----------------------------------------------------------  
 */
@IsTest
private class XC_LWC_MenuCtrlTest {
    @TestSetup
    static void setupTest() {
        setupHelper();
    }

    @IsTest
    static void testBehavior() {

    }

    // HELPER METHODS
    static void setupHelper() {

    }
}