/**
 * @FileName: XC_LWC_MenuCtrlHelper
 * @Description:
 * @Author: Graeme Ward
 * @ModificationLog:
 *-----------------------------------------------------------
 * Author            Date            Modification
 * Graeme Ward       8/16/2020         Created
 *-----------------------------------------------------------  
 */
public with sharing class XC_LWC_MenuCtrlHelper {

//    public static List<XC_LWC_MenuWrapper.MenuItem> getMenuItems(String menuName) {
//        XC_LWC_MenuWrapper menuWrapper = new XC_LWC_MenuWrapper(menuName);
//        return menuWrapper.menuItems;
//    }
}